title: Blacky's Blog
author: Blacky YG
theme: minima
email: tessilimi.hamidou@gmail.com
description: This is my personal blog. I will share contents about me, my different activities and my school projects

twitter_username: blacky_yg
github_username:  blacky-yg

show_excerpts: true # set to false to remove excerpts on the homepage
